//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utac.DataAccessLogic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaYou_dbEntities : DbContext
    {
        public TaYou_dbEntities()
            : base("name=TaYou_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
        public virtual DbSet<TBL_Data_Log> TBL_Data_Log { get; set; }
        public virtual DbSet<Tbl_UserTransaction> Tbl_UserTransaction { get; set; }
        public virtual DbSet<View_Tbl_UserTransaction> View_Tbl_UserTransaction { get; set; }
        public virtual DbSet<Tbl_Token> Tbl_Token { get; set; }
        public virtual DbSet<Tbl_Token_Operation> Tbl_Token_Operation { get; set; }
    }
}
