//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utac.DataAccessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Data_Log
    {
        public int id { get; set; }
        public string Operation { get; set; }
        public string Type { get; set; }
        public string Data_Log { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public string Create_By { get; set; }
    }
}
