//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nautilus.DataAccessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblForgetPassword
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> User_Guid { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
