//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nautilus.DataAccessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemServiceJobType
    {
        public System.Guid Guid { get; set; }
        public Nullable<int> ServiceJobTypeID { get; set; }
        public string ServiceJobTypeName { get; set; }
        public string ServiceJobTypeNameAbb { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<bool> FlagUsingAdhocJob { get; set; }
        public Nullable<bool> FlagUsingWithOldVersion { get; set; }
        public Nullable<System.Guid> SystemDisplayTextControlsName_Guid { get; set; }
        public Nullable<System.Guid> SystemDisplayTextControlsAbb_Guid { get; set; }
        public bool FlagUsingonSfoTicket { get; set; }
    }
}
