//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nautilus.DataAccessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemJobStatu
    {
        public System.Guid Guid { get; set; }
        public Nullable<int> StatusJobID { get; set; }
        public string StatusJobName { get; set; }
        public Nullable<System.Guid> SystemDisplayTextControlsLanguage_Guid { get; set; }
        public Nullable<bool> FlagScanByPreVault { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string PathIcon { get; set; }
        public Nullable<bool> FlagCloseRun { get; set; }
        public Nullable<bool> FlagUpdateJobClose { get; set; }
        public string ImagePathMVC { get; set; }
        public Nullable<bool> FlagIncidentStatus { get; set; }
    }
}
