//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nautilus.DataAccessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemDepositSlip_Regis_InputType
    {
        public System.Guid Guid { get; set; }
        public Nullable<int> InputTypeCode { get; set; }
        public Nullable<int> Parent_InputTypeCode { get; set; }
        public string InputTypeName { get; set; }
    }
}
