//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nautilus.DataAccessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SealItem
    {
        public System.Guid Guid { get; set; }
        public string ItemSealNo { get; set; }
        public Nullable<System.Guid> MasterCustomer_Guid { get; set; }
        public string CustomerFullName { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_Guid { get; set; }
        public string CustomerLocationName { get; set; }
        public Nullable<System.Guid> GroupingSet { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Process_Type { get; set; }
        public int ItemSealStatus { get; set; }
        public Nullable<bool> FlagCancel { get; set; }
        public System.Guid MasterInventoryType_Guid { get; set; }
        public string InventoryType_Name { get; set; }
        public Nullable<System.Guid> MasterCurrency_Guid { get; set; }
        public string MasterCurrencyAbbreviation { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
    }
}
