//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nautilus.DataAccessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ContainerSeal
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterContainer_Guid { get; set; }
        public string SealNo { get; set; }
        public string MasterCountryName { get; set; }
        public Nullable<System.Guid> MasterCountry_Guid { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public string SiteName { get; set; }
        public Nullable<System.Guid> MasterSafe_Guid { get; set; }
        public string Safe_Name { get; set; }
        public Nullable<System.Guid> MasterCustomer_Guid { get; set; }
        public string CustomerFullName { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_Guid { get; set; }
        public string BranchName { get; set; }
        public Nullable<System.Guid> MasterInventoryType_Guid { get; set; }
        public string InventoryType_Name { get; set; }
        public Nullable<int> ContainerStatusID { get; set; }
    }
}
